blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/[your-username]/[your-repo]/discussions
    about: Ask questions and discuss ideas
  - name: 📚 Documentation
    url: https://github.com/[your-username]/[your-repo]/wiki
    about: Check the documentation first
